/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "evcqpapvcvmljgqiuzsq"
// Use Vite env `VITE_SUPABASE_ANON_KEY`; leaving empty here removes old project reference
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2Y3FwYXB2Y3ZtbGpncWl1enNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3ODk2MzIsImV4cCI6MjA3ODM2NTYzMn0.U4XapYqi_4KAemNTwx88mLVBKVrzBp0_mMrIgZwcXa8"
